ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr
BOARD_TAG     = mega2560
OBJDIR        = build
CPPFLAGS      = -DDISABLE_BED=1

include $(ARDUINO_DIR)/Arduino.mk
